version: "2"

services:
  client:
    image: komvd/todo_list
    pull_policy: "never"
    env_file:
      - .env
    restart: "no"
    user: "root"
    volumes:
      - ./client:/app/client
      - ./node_modules:/app/node_modules
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
    ports:
      - 5000:5000
    environment:
      - CHOKIDAR_USEPOLLING = true
